# Generated by Django 4.2.5 on 2023-09-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Purpose', models.CharField(max_length=120)),
                ('Amount', models.IntegerField(max_length=10)),
                ('Reason', models.CharField(max_length=500)),
            ],
        ),
    ]
